baseurl = "https://ruanviljoen.com"
title = "RUANVILJOEN.COM"
theme = "hugo-coder-forked"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

#enableGitInfo = true

[params]
author = "Ruan Viljoen"
info = ["Technologist"]
description = "Ruan Viljoen's personal page"
keywords = "businesscard,personal"
avatarurl = "images/avatar.jpg"

since = 2023
enableTwemoji = true
colorScheme = "auto"
hidecolorschemetoggle = false
# Git Commit in Footer, uncomment the line below to enable it
commit = "https://github.com/rviljoen/ruanviljoen.com/tree/"
powered_by = true
# Series see also post count
maxSeeAlsoItems = 5

[taxonomies]
tag = "tags"
author = "authors"

# Social links
[[params.social]]
name = "Github"
icon = "fa fa-github fa-2x"
weight = 1
url = "https://github.com/rviljoen/"
target = "_blank"
[[params.social]]
name = "Linkedin"
icon = "fa fa-linkedin fa-2x"
weight = 5
url = "https://www.linkedin.com/in/ruanviljoen/"
target = "_blank"
[[params.social]]
name = "info@ruanviljoen.com"
icon = "fa fa-envelope fa-2x"
weight = 6
url = "mailto:info@ruanviljoen.com"
target = "_blank"

# Menu links
[[languages.en.menu.main]]
name = "Home"
weight = 1
url  = "/"
[[languages.en.menu.main]]
name = "About"
weight = 2
url = "about/"